(()=>{(function(){"use strict";let S=window.ZaaNetConfig.getApiConfig(),i=null,l=null,u=null,d=new URLSearchParams(window.location.search),h=d.get("sessionId"),f=d.get("contractId"),C=d.get("mac")||d.get("clientmac")||"$clientmac",T=d.get("ip")||d.get("clientip")||"$clientip",P=C.startsWith("$")?null:C,I=T.startsWith("$")?"":T;function e(t){let n=document.getElementById(t);if(!n)throw new Error(`Element with id "${t}" not found`);return n}k();async function k(){if(console.log("[Session] Initializing dashboard..."),!h||!f){D("No session information provided. Please authenticate first.");return}await w(),l=setInterval(w,3e4),u=setInterval($,1e3)}async function w(){try{if(console.log("[Session] Fetching session data..."),!h||!f)throw new Error("Missing sessionId or contractId");let t=await fetch(`${S.baseUrl}${S.sessionInfoEndpoint}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userIP:I,sessionId:h,contractId:f})});if(!t.ok)throw new Error(`HTTP ${t.status}`);if(i=await t.json(),!i.success)throw new Error(i.error||"Failed to load session");console.log("[Session] Data loaded:",i),F(),e("loadingState").style.display="none",e("dashboard").style.display="block"}catch(t){console.error("[Session] Error loading data:",t),D("Failed to load session data. Please refresh the page.")}}function F(){if(!i)return;let t=i.session;if(!t){console.error("[Session] No session data in response",i);return}let n=t.duration||0;e("planName").textContent=n>0?`${n.toFixed(1)} Hours`:"Unknown";let o=t.voucherCode||Array.isArray(t.vouchers)&&t.vouchers[0]||"--";e("voucherCode").textContent=String(o);let r=t.startTime?new Date(t.startTime):new Date,s=t.endTime?new Date(t.endTime):t.remainingTimeSecs?new Date(Date.now()+t.remainingTimeSecs*1e3):new Date;e("startTime").textContent=v(r),e("expireTime").textContent=v(s),e("macAddress").textContent=P||"--",e("ipAddress").textContent=t.userIP||I||"--",e("routerId").textContent=f||"--";let a=b(t.analytics&&t.analytics.bytesDownloaded||0),c=b(t.analytics&&t.analytics.bytesUploaded||0),p=a+c;e("dataDownloaded").textContent=a.toFixed(2),e("dataUploaded").textContent=c.toFixed(2),e("dataTotalUsage").textContent=p.toFixed(2);let g=t.actualDurationSeconds?Math.floor(t.actualDurationSeconds/60):Math.floor((Date.now()-r.getTime())/6e4);e("sessionDuration").textContent=Math.max(0,g).toString(),A(c,a),$()}function $(){if(!i)return;let t=i.session;if(!t)return;let o=(t.remainingTimeSecs||0)*1e3;if(o<=0){e("timeRemaining").textContent="00:00:00",e("timeBreakdown").textContent="Session expired",e("timeProgress").style.width="0%";let E=document.querySelector(".status-badge");E&&(E.innerHTML=`
          <span class="status-indicator" style="background: #dc3545;"></span>
          <span>Expired</span>
        `),u&&clearInterval(u),l&&clearInterval(l);return}let r=Math.floor(o/1e3),s=Math.floor(r/3600),a=Math.floor(r%3600/60),c=r%60,p=`${y(s)}:${y(a)}:${y(c)}`;e("timeRemaining").textContent=p;let g=Math.floor(s/24),M=s%24,m="";g>0?m=`${g} day${g>1?"s":""}, ${M} hour${M!==1?"s":""}`:s>0?m=`${s} hour${s!==1?"s":""}, ${a} minute${a!==1?"s":""}`:m=`${a} minute${a!==1?"s":""}, ${c} second${c!==1?"s":""}`,e("timeBreakdown").textContent=m;let B=(t.duration||0)*3600*1e3,L=B>0?Math.max(0,Math.min(100,o/B*100)):0;e("timeProgress").style.width=L+"%";let x=document.querySelector(".timer-display");x&&(o<6e5?x.style.background="linear-gradient(135deg, #dc3545 0%, #c82333 100%)":o<36e5&&(x.style.background="linear-gradient(135deg, #ffc107 0%, #ff9800 100%)"))}function A(t,n){let o=Math.max(t,n,1),r=t/o*100,s=n/o*100;e("uploadBar").style.height=r+"px",e("downloadBar").style.height=s+"px",e("uploadBarText").textContent=t.toFixed(1)+"MB",e("downloadBarText").textContent=n.toFixed(1)+"MB"}async function H(t){if(console.log("[Session] Manual refresh requested"),await w(),t&&t.target){let n=t.target,o=n.textContent||"";n.textContent="Refreshing...",n.disabled=!0,setTimeout(()=>{n.textContent=o,n.disabled=!1},1e3)}}async function U(){if(confirm("Are you sure you want to disconnect? You will need to enter a new voucher to reconnect.")){console.log("[Session] Disconnecting...");try{alert("You have been disconnected. Redirecting..."),window.location.href="/"}catch(t){console.error("[Session] Disconnect error:",t),alert("Failed to disconnect. Please try again.")}}}function D(t){let n=e("loadingState");n.innerHTML=`
      <div class="error-message">
        <strong>Error:</strong> ${t}
      </div>
      <a href="/" class="btn btn-primary">Back to Login</a>
    `}function b(t){return t/(1024*1024)}function v(t){return t.toLocaleString("en-US",{year:"numeric",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}function y(t){return t.toString().padStart(2,"0")}window.refreshSession=H,window.disconnectSession=U,window.addEventListener("beforeunload",()=>{l&&clearInterval(l),u&&clearInterval(u)})})();})();
