"use strict";(()=>{(function(){"use strict";let x=window.ZaaNetConfig.getApiConfig(),i=null,l=null,u=null,d=new URLSearchParams(window.location.search),h=d.get("sessionId"),m=d.get("contractId"),T=d.get("mac")||d.get("clientmac")||"$clientmac",I=d.get("ip")||d.get("clientip")||"$clientip",H=T.startsWith("$")?null:T,v=I.startsWith("$")?"":I;function t(e){let n=document.getElementById(e);if(!n)throw new Error(`Element with id "${e}" not found`);return n}B();async function B(){if(console.log("[Session] Initializing dashboard..."),!h||!m){b("No session information provided. Please authenticate first.");return}await p(),l=setInterval(p,3e4),u=setInterval(C,1e3)}async function p(){try{if(console.log("[Session] Fetching session data..."),!h||!m)throw new Error("Missing sessionId or contractId");let e=await fetch(`${x.baseUrl}${x.sessionInfoEndpoint}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userIP:v,sessionId:h,contractId:m})});if(!e.ok)throw new Error(`HTTP ${e.status}`);if(i=await e.json(),!i.success)throw new Error(i.error||"Failed to load session");console.log("[Session] Data loaded:",i),L(),t("loadingState").style.display="none",t("dashboard").style.display="block"}catch(e){console.error("[Session] Error loading data:",e),b("Failed to load session data. Please refresh the page.")}}function L(){if(!i)return;let e=i.session;if(!e){console.error("[Session] No session data in response",i);return}let n=e.duration||0;t("planName").textContent=n>0?`${n.toFixed(1)} Hours`:"Unknown";let o=e.voucherCode||Array.isArray(e.vouchers)&&e.vouchers[0]||"--";t("voucherCode").textContent=String(o);let a=e.startTime?new Date(e.startTime):new Date,s=e.endTime?new Date(e.endTime):e.remainingTimeSecs?new Date(Date.now()+e.remainingTimeSecs*1e3):new Date;t("startTime").textContent=$(a),t("expireTime").textContent=$(s),t("macAddress").textContent=H||"--",t("ipAddress").textContent=e.userIP||v||"--",t("routerId").textContent=m||"--";let r=M(e.analytics?.bytesDownloaded||0),c=M(e.analytics?.bytesUploaded||0),S=r+c;t("dataDownloaded").textContent=r.toFixed(2),t("dataUploaded").textContent=c.toFixed(2),t("dataTotalUsage").textContent=S.toFixed(2);let f=e.actualDurationSeconds?Math.floor(e.actualDurationSeconds/60):Math.floor((Date.now()-a.getTime())/6e4);t("sessionDuration").textContent=Math.max(0,f).toString(),k(c,r),C()}function C(){if(!i)return;let e=i.session;if(!e)return;let o=(e.remainingTimeSecs||0)*1e3;if(o<=0){t("timeRemaining").textContent="00:00:00",t("timeBreakdown").textContent="Session expired",t("timeProgress").style.width="0%";let P=document.querySelector(".status-badge");P&&(P.innerHTML=`
          <span class="status-indicator" style="background: #dc3545;"></span>
          <span>Expired</span>
        `),u&&clearInterval(u),l&&clearInterval(l);return}let a=Math.floor(o/1e3),s=Math.floor(a/3600),r=Math.floor(a%3600/60),c=a%60,S=`${y(s)}:${y(r)}:${y(c)}`;t("timeRemaining").textContent=S;let f=Math.floor(s/24),D=s%24,g="";f>0?g=`${f} day${f>1?"s":""}, ${D} hour${D!==1?"s":""}`:s>0?g=`${s} hour${s!==1?"s":""}, ${r} minute${r!==1?"s":""}`:g=`${r} minute${r!==1?"s":""}, ${c} second${c!==1?"s":""}`,t("timeBreakdown").textContent=g;let E=(e.duration||0)*3600*1e3,A=E>0?Math.max(0,Math.min(100,o/E*100)):0;t("timeProgress").style.width=A+"%";let w=document.querySelector(".timer-display");w&&(o<6e5?w.style.background="linear-gradient(135deg, #dc3545 0%, #c82333 100%)":o<36e5&&(w.style.background="linear-gradient(135deg, #ffc107 0%, #ff9800 100%)"))}function k(e,n){let o=Math.max(e,n,1),a=e/o*100,s=n/o*100;t("uploadBar").style.height=a+"px",t("downloadBar").style.height=s+"px",t("uploadBarText").textContent=e.toFixed(1)+"MB",t("downloadBarText").textContent=n.toFixed(1)+"MB"}async function F(e){if(console.log("[Session] Manual refresh requested"),await p(),e&&e.target){let n=e.target,o=n.textContent||"";n.textContent="Refreshing...",n.disabled=!0,setTimeout(()=>{n.textContent=o,n.disabled=!1},1e3)}}async function R(){if(confirm("Are you sure you want to disconnect? You will need to enter a new voucher to reconnect.")){console.log("[Session] Disconnecting...");try{alert("You have been disconnected. Redirecting..."),window.location.href="/"}catch(e){console.error("[Session] Disconnect error:",e),alert("Failed to disconnect. Please try again.")}}}function b(e){let n=t("loadingState");n.innerHTML=`
      <div class="error-message">
        <strong>Error:</strong> ${e}
      </div>
      <a href="/" class="btn btn-primary">Back to Login</a>
    `}function M(e){return e/(1024*1024)}function $(e){return e.toLocaleString("en-US",{year:"numeric",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}function y(e){return e.toString().padStart(2,"0")}window.refreshSession=F,window.disconnectSession=R,window.addEventListener("beforeunload",()=>{l&&clearInterval(l),u&&clearInterval(u)})})();})();
